name: 'Run Percy'
description: 'Run Percy'
inputs:
  token:
    description: 'percy token'
runs:
  using: 'composite'
  steps:
    - name: Install Playwright Browsers
      shell: bash
      run: pnpm exec playwright install chromium --with-deps

    - name: Create snapshots
      shell: bash
      run: pnpm visual-regression --filter @siemens/ix
      env:
        PERCY_TOKEN: ${{ inputs.token }}
