name: build

on:
  push:
    branches:
      - 'main'
      - 'release/*'
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/turbo

      - name: Build
        run: pnpm build --cache-dir=.turbo --filter \!documentation

  unit:
    needs: [build]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/turbo

      - name: Test
        run: pnpm run test --cache-dir=.turbo --filter @siemens/ix --filter @siemens/ix-angular

  visual-testing:
    needs: [build]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    strategy:
      fail-fast: false
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/turbo

      - name: Visual Regression
        run: pnpm run visual-regression --cache-dir=.turbo --filter @siemens/ix --filter @siemens/ix-aggrid -- --shard ${{ matrix.shard }}

      - name: Upload blob report to GitHub Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: all-blob-reports
          path: |
            ./packages/core/blob-report
            ./packages/aggrid/blob-report
          retention-days: 1

  merge-reports:
    # Merge reports after playwright-tests, even if some shards have failed
    if: always()
    needs: [visual-testing]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/turbo

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v3
        with:
          name: all-blob-reports
          path: |
            ./packages/core/all-blob-report
            ./packages/aggrid/all-blob-report

      - name: Merge into HTML Report
        run: |
          pnpm exec playwright merge-reports --reporter html ./packages/core/all-blob-report

      - name: Merge into HTML Report
        run: |
          pnpm exec playwright merge-reports --reporter html ./packages/aggrid/all-blob-report

      # - name: Upload HTML report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: html-report--attempt-${{ github.run_attempt }}
      #     path: playwright-report
      #     retention-days: 14

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/turbo
      - name: Lint
        run: pnpm lint
