name: nightly

on:
  push:
    branches:
      - 'nightly-test'
  workflow_dispatch:

jobs:
  deploy_nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy build files
        shell: bash
        run: |
          rm -rf .git
          rm -rf .gitignore

      - uses: ./.github/workflows/actions/turbo

      - name: Build
        run: pnpm build --cache-dir=.turbo --filter \!documentation

      - name: Prepare ix repo
        uses: actions/checkout@v3
        with:
          path: 'nightly_store_ix'
          ref: 'ix'
          repository: 'danielleroux/ix-nightlies'
          token: ${{ secrets. NIGHTLY_STORE }}
          fetch-depth: 0
          persist-credentials: true

      - name: Copy build files
        shell: bash
        run: |
          cd ./packages/core
          TAR_FILE=$(pnpm pack)
          tar -xvf $TAR_FILE -C ../../nightly_store_ix

      - name: Debug
        shell: bash
        working-directory: nightly_store_ix
        run: |
          git config --global user.name "ix builder [bot]"
          git config --global user.email "<>"
          mv ./package/* .
          git add -A
          git commit -m "snapshot: some info and <date>"
